
trigger:
- main

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: "build"
  displayName: "构建阶段"
  jobs:
  - job: "buildFrontend"
    displayName: "打包前端代码"
    steps:
    - script: echo "打包前端代码...."
  - job: "buildBackend"
    displayName: "打包后端代码"
    steps:
    - script: echo "打包后端代码..."

- stage: "deploy"
  dependsOn: "build"
  displayName: "发布阶段"
  jobs:
  - job: "deployFrontend"
    displayName: "发布前端代码"
    steps:
    - script: echo "发布前端代码..."
  - job: "deployBackend"
    displayName: "发布后端代码"
    steps:
    - script: echo "发布后端代码..."

- stage: "test"
  dependsOn: "build"
  displayName: "测试阶段"
  jobs:
  - job: "testApi"
    displayName: "测试接口"
    steps:
    - script: echo "测试接口..."